<?php
SEO::set('meta_title', 'Meta Ads for D2C Brands: Step-by-Step Guide | ' . SITE_NAME);
SEO::set('meta_description', 'Build profitable Meta ad campaigns for your Shopify D2C brand with this step-by-step guide to tracking, structure, creative, budgets, testing, and scaling.');
SEO::set('canonical_url', url('resources/meta-ads-d2c-guide'));
SEO::set('og_title', 'Meta Ads for D2C Brands: The Practical Setup Guide');
SEO::set('og_description', 'A clear framework for tracking, campaigns, creative testing, measurement, and profitable scaling.');
$steps = [
 ['01','Get the economics right','Calculate contribution margin, break-even ROAS, allowable customer acquisition cost, and a target that leaves room for overhead. Use net revenue after discounts, cancellations, and refunds—not dashboard revenue alone.',['Know AOV and product margin','Set break-even and target ROAS','Define first-order vs lifetime-value targets']],
 ['02','Build a trustworthy data foundation','Connect the Meta Pixel to Shopify, configure Conversions API where available, verify your domain, prioritize key web events, and test the full purchase journey. Use consistent UTMs so analytics and store orders can be reconciled.',['Test ViewContent, AddToCart, InitiateCheckout, and Purchase','Check value and currency parameters','Exclude test and duplicate purchases']],
 ['03','Prepare the offer and landing page','Ads amplify the buying experience; they do not repair it. Make the product promise, proof, price, shipping, returns, delivery estimate, and primary action obvious on mobile.',['Match ad promise to landing page','Place reviews and objections near the CTA','Check speed and checkout on a real phone']],
 ['04','Create ads around customer angles','Develop distinct reasons to buy, then express each angle through multiple formats. Product demos, founder stories, customer proof, comparisons, problem-solution videos, and statics give the system meaningful options.',['One main idea per ad','Show product or outcome early','Add captions and mobile-safe text']],
 ['05','Launch a simple campaign structure','For ecommerce sales, use a Sales campaign optimized for Purchase when you have reliable purchase tracking. Keep prospecting consolidated enough to learn and separate only when budget, geography, offer, or business logic truly differs.',['Choose the conversion location and Purchase event','Use broad or justified audience controls','Start with automatic placements unless evidence says otherwise']],
 ['06','Set a learning-friendly budget','Budget must generate enough opportunities to judge an ad without putting cash flow at risk. Base it on allowable CPA and testing volume—not an arbitrary daily number.',['Decide maximum loss per test','Avoid constant edits after launch','Record hypothesis, spend, and decision date']],
 ['07','Read the funnel, not one metric','ROAS is an outcome. Diagnose delivery, thumb-stop/attention, click quality, product-page conversion, checkout completion, CPA, refund rate, and contribution profit together.',['High CPM alone does not prove a problem','Clicks without purchases often signal message or site friction','Judge blended business impact alongside platform attribution']],
 ['08','Scale winners without starving discovery','Increase spend in controlled steps when performance remains above target and fulfillment can handle demand. Continue creative testing because fatigue, competition, and demand change over time.',['Scale budget progressively','Refresh losing hooks before rebuilding everything','Protect a recurring creative-test budget']],
];
$faqs=[
 ['question'=>'Which Meta campaign objective should a D2C brand use?','answer'=>'An ecommerce brand seeking online purchases should generally use the Sales objective with the website or appropriate shop as the conversion location, then optimize for Purchase when reliable purchase data is available.'],
 ['question'=>'How much should I spend on Meta ads initially?','answer'=>'Set a testing budget from your allowable CPA and the number of conversions needed to make a decision. A smaller brand should test fewer variables with enough budget per test rather than spreading money across many ad sets.'],
 ['question'=>'Should I use broad audiences or interests?','answer'=>'Broad targeting is a strong baseline when tracking, creative, and conversion volume are healthy. Interest or custom audiences can still be useful when they represent a clear hypothesis, market constraint, or retargeting group.'],
 ['question'=>'How many creatives should I test?','answer'=>'Test enough ads to represent genuinely different hooks, formats, and customer angles without fragmenting budget. Three to six purposeful ads in a test is often more useful than dozens of minor variations.'],
 ['question'=>'When should I scale a Meta campaign?','answer'=>'Scale after purchases show that CPA or contribution profit is consistently within target, tracking is credible, and operations can fulfill added demand. Increase budgets gradually and monitor marginal—not only average—returns.'],
];
$schemas=[SEO::breadcrumbSchema([['name'=>'Home','url'=>url('/')],['name'=>'Resources','url'=>url('resources')],['name'=>'Meta Ads for D2C Brands','url'=>url('resources/meta-ads-d2c-guide')]]),SEO::faqSchema($faqs),json_encode(['@context'=>'https://schema.org','@type'=>'HowTo','name'=>'How to set up Meta ads for a D2C ecommerce brand','description'=>'An eight-step framework for profitable Meta advertising.','totalTime'=>'P14D','step'=>array_map(fn($s)=>['@type'=>'HowToStep','position'=>(int)$s[0],'name'=>$s[1],'text'=>$s[2]],$steps)],JSON_UNESCAPED_SLASHES)];
ob_start();
?>
<section class="bg-slate-950 py-16 lg:py-24 relative overflow-hidden"><div class="absolute inset-0 opacity-30" style="background:radial-gradient(circle at 15% 20%,#2563eb,transparent 30%),radial-gradient(circle at 85% 75%,#7c3aed,transparent 30%)"></div><div class="relative max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><a href="<?= url('resources') ?>" class="text-sm text-blue-300">&larr; Back to resources</a><p class="mt-6 text-xs font-bold uppercase tracking-[.2em] text-blue-400">Free D2C growth guide</p><h1 class="mt-3 text-4xl sm:text-5xl lg:text-6xl font-extrabold text-white leading-tight">Meta Ads for D2C Brands</h1><p class="mt-6 text-lg text-slate-300 max-w-3xl mx-auto">A step-by-step system for setting up, testing, measuring, and scaling Shopify campaigns profitably.</p></div></section>

<main class="bg-gray-50 py-14 lg:py-20"><div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><div class="grid lg:grid-cols-4 gap-8 items-start">
<aside class="hidden lg:block lg:sticky lg:top-24"><p class="text-xs font-bold uppercase tracking-wider text-gray-500 mb-4">In this guide</p><nav class="space-y-1"><?php foreach($steps as $step): ?><a href="#step-<?= $step[0] ?>" class="block px-3 py-2 text-sm text-gray-600 hover:text-blue-700 hover:bg-blue-50 rounded-lg"><?= $step[0] ?>. <?= clean($step[1]) ?></a><?php endforeach; ?><a href="#metrics" class="block px-3 py-2 text-sm text-gray-600 hover:text-blue-700 hover:bg-blue-50 rounded-lg">Metrics</a><a href="#faq" class="block px-3 py-2 text-sm text-gray-600 hover:text-blue-700 hover:bg-blue-50 rounded-lg">FAQs</a></nav></aside>
<div class="lg:col-span-3">
<section class="bg-blue-50 border border-blue-100 rounded-2xl p-6 lg:p-8 mb-10"><h2 class="text-xl font-bold text-gray-900 mb-2">The profitable Meta ads framework</h2><p class="text-gray-700 leading-relaxed">Profitable D2C advertising requires four systems to work together: sound unit economics, accurate measurement, high-volume creative learning, and a store that converts. Start with business margin, optimize toward purchases, and scale only while marginal contribution remains healthy.</p></section>

<div class="space-y-7"><?php foreach($steps as $step): ?><section id="step-<?= $step[0] ?>" class="scroll-mt-24 bg-white border border-gray-200 rounded-2xl p-6 lg:p-8"><div class="flex gap-5"><span class="text-3xl font-extrabold text-blue-200"><?= $step[0] ?></span><div><h2 class="text-2xl font-bold text-gray-900 mb-3"><?= clean($step[1]) ?></h2><p class="text-gray-600 leading-relaxed mb-5"><?= clean($step[2]) ?></p><ul class="grid sm:grid-cols-3 gap-3"><?php foreach($step[3] as $item): ?><li class="p-3 text-sm text-gray-700 bg-gray-50 rounded-xl">✓ <?= clean($item) ?></li><?php endforeach; ?></ul></div></div></section><?php endforeach; ?></div>

<section id="metrics" class="scroll-mt-24 mt-12"><h2 class="text-3xl font-extrabold text-gray-900 mb-6">Metrics that make the diagnosis useful</h2><div class="overflow-x-auto bg-white border border-gray-200 rounded-2xl"><table class="w-full text-sm"><thead class="bg-gray-50 text-left"><tr><th class="p-4">Metric</th><th class="p-4">What it tells you</th><th class="p-4">Use it to ask</th></tr></thead><tbody class="divide-y divide-gray-100"><?php foreach([
 ['CPM','Cost to reach people','Is the auction expensive, or is delivery constrained?'],['Outbound CTR','Ability to earn a site visit','Does the hook and offer create qualified curiosity?'],['Landing-page conversion','Store effectiveness','Does the page fulfil the ad promise and remove objections?'],['CPA','Cost to acquire an order','Is acquisition within allowable unit economics?'],['MER / blended ROAS','Total revenue efficiency','Is the overall business growing efficiently across channels?'],['Contribution profit','Cash generated after variable costs','Are we making money, not merely reporting revenue?']
] as $row): ?><tr><?php foreach($row as $cell): ?><td class="p-4 text-gray-600 first:font-semibold first:text-gray-900"><?= clean($cell) ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div></section>

<section class="mt-12 grid md:grid-cols-2 gap-6"><div class="bg-emerald-50 border border-emerald-100 rounded-2xl p-7"><h2 class="text-xl font-bold text-gray-900 mb-4">Pre-launch check</h2><ul class="space-y-3 text-sm text-gray-700"><li>✓ Purchase event fires once with correct value</li><li>✓ Product page matches the creative promise</li><li>✓ UTMs and naming are consistent</li><li>✓ Target and break-even CPA are documented</li><li>✓ Inventory, support, and fulfillment are ready</li></ul></div><div class="bg-rose-50 border border-rose-100 rounded-2xl p-7"><h2 class="text-xl font-bold text-gray-900 mb-4">Avoid these traps</h2><ul class="space-y-3 text-sm text-gray-700"><li>× Changing settings before data can accumulate</li><li>× Splitting a small budget across many ad sets</li><li>× Calling platform revenue “profit”</li><li>× Using fake urgency or unsupported claims</li><li>× Scaling while returns or fulfillment failures rise</li></ul></div></section>

<section id="faq" class="scroll-mt-24 mt-16"><h2 class="text-3xl font-extrabold text-gray-900 text-center mb-8">Meta ads FAQs</h2><div class="space-y-4"><?php foreach($faqs as $faq): ?><details class="bg-white border border-gray-200 rounded-xl"><summary class="p-5 font-semibold cursor-pointer"><?= clean($faq['question']) ?></summary><p class="px-5 pb-5 text-gray-600 leading-relaxed"><?= clean($faq['answer']) ?></p></details><?php endforeach; ?></div></section>
<p class="mt-8 text-xs text-gray-500">Platform interfaces and policies change. Confirm implementation details in the current Meta Business Help Center and your account before launch.</p>
</div></div></div></main>
<section class="bg-blue-700 py-14"><div class="max-w-3xl mx-auto px-4 text-center"><h2 class="text-3xl font-extrabold text-white">Want a team to run the system?</h2><p class="text-blue-100 mt-3 mb-7">We connect creative testing, media buying, Shopify conversion, and unit economics.</p><a href="<?= url('services/performance-marketing') ?>" class="inline-flex px-7 py-3.5 bg-white text-blue-700 font-semibold rounded-xl">Explore performance marketing</a></div></section>
<?php $pageContent=ob_get_clean(); SEO::renderSchemas($schemas); include __DIR__.'/../../includes/components/layout.php';
