<?php
SEO::set('meta_title', '50-Point Shopify Launch Checklist for New Stores | ' . SITE_NAME);
SEO::set('meta_description', 'Use this interactive 50-point Shopify launch checklist to verify products, payments, shipping, legal pages, tracking, SEO, mobile UX, and checkout before launch.');
SEO::set('canonical_url', url('resources/shopify-launch-checklist'));
SEO::set('og_title', 'The Complete 50-Point Shopify Launch Checklist');
SEO::set('og_description', 'Track every essential task before launching your Shopify store. Progress saves automatically.');
$groups=[
 'foundation'=>['Store foundations','Set the account, market, and domain basics before polishing the storefront.',[
  'Confirm business name, legal entity, address, email, and phone','Connect the final custom domain and set it as primary','Set store currency, time zone, unit system, and order ID format','Configure selling markets and languages you actually support','Create staff accounts with minimum required permissions','Remove storefront password only when launch checks are complete']],
 'brand'=>['Brand, theme & navigation','Make the store recognizable, consistent, and easy to navigate on every screen.',[
  'Upload crisp logo, favicon, and social sharing image','Set consistent colors, typography, buttons, and spacing','Build a clear header with search, account, cart, and primary categories','Create footer links for support, policies, contact, and social profiles','Check homepage hierarchy, calls to action, and empty sections','Review every key template on mobile, tablet, and desktop']],
 'products'=>['Products & merchandising','Give customers everything they need to choose the right product confidently.',[
  'Write unique product titles and benefit-led descriptions','Upload optimized images with meaningful alt text','Add price, compare-at price, cost, SKU, barcode, and inventory','Check every variant, swatch, size, and unavailable-state behavior','Create logical collections and assign products correctly','Add sizing, ingredients, materials, care, or compatibility details','Show delivery, return, warranty, and COD information near purchase','Set product SEO title, description, and clean URL handle']],
 'checkout'=>['Payments & checkout','Make paying simple, trustworthy, and fully tested.',[
  'Activate and verify every intended payment provider','Configure UPI, cards, wallets, COD, or local methods as required','Set customer contact, address, tipping, and marketing-consent options','Customize checkout logo, colors, support details, and policies','Place a real test order for each major payment method','Verify failed, pending, refunded, cancelled, and COD order flows']],
 'operations'=>['Shipping, tax & operations','Ensure every accepted order can be priced, packed, shipped, and supported.',[
  'Create accurate shipping zones, rates, thresholds, and exclusions','Test shipping rates for representative PIN codes or postcodes','Configure package dimensions and product weights','Review tax registrations, prices, invoices, and tax overrides with an adviser','Connect fulfillment, shipping, inventory, and returns systems','Set low-stock rules, overselling behavior, and inventory locations','Write internal steps for packing, NDR, returns, refunds, and support']],
 'trust'=>['Trust, legal & accessibility','Protect the customer and business while removing reasons to hesitate.',[
  'Publish contact, about, privacy, terms, shipping, and return pages','Use business-specific policies instead of unedited generators','Display realistic delivery estimates and return conditions','Check contrast, keyboard navigation, labels, headings, and image alt text','Add authentic reviews, guarantees, certifications, and support channels','Verify cookie consent and marketing opt-in behavior where required']],
 'marketing'=>['Marketing, analytics & SEO','Make launch traffic measurable and pages discoverable.',[
  'Connect analytics and verify ecommerce events','Install ad pixels and server-side tracking where appropriate','Test product-view, add-to-cart, checkout, purchase, and lead events','Set unique homepage SEO title, meta description, and social preview','Submit sitemap and verify search-engine webmaster tools','Prepare welcome, cart recovery, order, review, and support messages']],
 'testing'=>['Quality assurance & launch','Run the store like a customer before sending real traffic.',[
  'Check links, forms, search, filters, discount codes, and error pages','Test full purchase and post-purchase journeys on real mobile devices','Review speed on homepage, collection, product, cart, and landing pages','Proofread prices, claims, dates, contact details, and automated messages','Back up the theme, document launch metrics, and monitor the first orders']],
];
$faqs=[
 ['question'=>'What should I check before launching a Shopify store?','answer'=>'Verify store settings, domain, theme, products, inventory, payments, checkout, shipping, tax, policies, analytics, SEO, mobile usability, speed, and complete order flows. Place real test orders before removing the storefront password.'],
 ['question'=>'How long does a Shopify store launch take?','answer'=>'A simple store can be launch-ready in a few weeks, while a large catalog or custom build may take several months. Product data, content, integrations, and operational readiness usually determine the timeline more than theme installation.'],
 ['question'=>'Can I launch Shopify before every task is complete?','answer'=>'Launch only when payment, pricing, product accuracy, fulfillment, legal, support, security, and customer-critical testing are ready. Lower-priority content or enhancements can follow if their absence does not mislead or block customers.'],
 ['question'=>'How do I test a Shopify store before launch?','answer'=>'Preview on real devices, test navigation and forms, use payment-provider test mode when available, place test orders, verify notifications and fulfillment, test refunds and discounts, and ask someone unfamiliar with the build to complete a purchase.'],
];
$allItems=[];foreach($groups as $key=>$group){foreach($group[2] as $item)$allItems[]=['@type'=>'ListItem','position'=>count($allItems)+1,'name'=>$item];}
$schemas=[SEO::breadcrumbSchema([['name'=>'Home','url'=>url('/')],['name'=>'Resources','url'=>url('resources')],['name'=>'Shopify Launch Checklist','url'=>url('resources/shopify-launch-checklist')]]),SEO::faqSchema($faqs),json_encode(['@context'=>'https://schema.org','@type'=>'ItemList','name'=>'50-Point Shopify Launch Checklist','numberOfItems'=>50,'itemListElement'=>$allItems],JSON_UNESCAPED_SLASHES)];
ob_start();
?>
<section class="bg-gradient-to-br from-purple-950 via-indigo-950 to-slate-950 py-16 lg:py-24"><div class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><a href="<?= url('resources') ?>" class="text-sm text-purple-300">&larr; Back to resources</a><p class="mt-6 text-xs font-bold uppercase tracking-[.2em] text-purple-400">Interactive launch resource</p><h1 class="mt-3 text-4xl sm:text-5xl lg:text-6xl font-extrabold text-white">50-Point Shopify Launch Checklist</h1><p class="mt-6 text-lg text-slate-300 max-w-3xl mx-auto">Cover the details that protect conversion, measurement, operations, and customer trust before your store goes live.</p></div></section>

<main class="bg-gray-50 py-10 lg:py-16"><div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
<section class="bg-white border border-gray-200 rounded-2xl p-5 sm:p-7 shadow-sm mb-8 sticky top-0 z-30"><div class="flex flex-col md:flex-row md:items-center gap-5"><div class="flex-1"><div class="flex items-center justify-between mb-2"><span id="progress-label" class="font-semibold text-gray-900">0 of 50 complete</span><span id="progress-percent" class="text-sm font-bold text-purple-700">0%</span></div><div class="h-3 bg-gray-100 rounded-full overflow-hidden"><div id="progress-bar" class="h-full bg-gradient-to-r from-purple-600 to-indigo-500 rounded-full transition-all" style="width:0%"></div></div><p class="text-xs text-gray-500 mt-2">Progress is saved automatically on this device.</p></div><div class="flex gap-2"><button id="print-checklist" type="button" class="px-4 py-2.5 text-sm font-semibold border border-gray-200 rounded-xl hover:bg-gray-50">Print</button><button id="reset-checklist" type="button" class="px-4 py-2.5 text-sm font-semibold text-red-600 border border-red-100 rounded-xl hover:bg-red-50">Reset</button></div></div></section>

<div class="flex gap-2 overflow-x-auto pb-3 mb-7" aria-label="Filter checklist"><button data-filter="all" class="filter-button active px-4 py-2 text-sm font-semibold rounded-full bg-purple-600 text-white min-w-max">All 50</button><?php foreach($groups as $key=>$group): ?><button data-filter="<?= $key ?>" class="filter-button px-4 py-2 text-sm font-semibold rounded-full bg-white text-gray-700 border border-gray-200 min-w-max"><?= clean($group[0]) ?></button><?php endforeach; ?></div>

<div id="checklist-groups" class="space-y-7"><?php $n=1;foreach($groups as $key=>$group): ?><section class="checklist-group bg-white border border-gray-200 rounded-2xl overflow-hidden" data-group="<?= $key ?>"><header class="p-6 bg-gradient-to-r from-purple-50 to-white border-b border-gray-100"><div class="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-2"><div><p class="text-xs font-bold uppercase tracking-wider text-purple-600"><?= count($group[2]) ?> checks</p><h2 class="text-2xl font-bold text-gray-900 mt-1"><?= clean($group[0]) ?></h2><p class="text-sm text-gray-600 mt-2"><?= clean($group[1]) ?></p></div><span class="group-progress text-sm font-semibold text-gray-500">0/<?= count($group[2]) ?></span></div></header><div class="divide-y divide-gray-100"><?php foreach($group[2] as $item): ?><label class="check-item flex gap-4 p-5 hover:bg-purple-50/40 cursor-pointer"><input type="checkbox" data-id="launch-<?= $n ?>" class="check-box mt-0.5 w-5 h-5 accent-purple-600 shrink-0"><span class="flex-1"><span class="text-xs font-bold text-gray-400 mr-2"><?= str_pad($n,2,'0',STR_PAD_LEFT) ?></span><span class="item-text text-gray-700 leading-relaxed"><?= clean($item) ?></span></span></label><?php $n++;endforeach; ?></div></section><?php endforeach; ?></div>

<section class="mt-14 grid lg:grid-cols-2 gap-6"><div class="bg-emerald-50 border border-emerald-100 rounded-2xl p-7"><h2 class="text-xl font-bold text-gray-900 mb-3">Launch gate: must be ready</h2><p class="text-sm text-gray-600 leading-relaxed">Correct products and pricing, working payment and checkout, accurate shipping and tax, legal policies, order fulfillment, customer support, data security, and a tested purchase journey.</p></div><div class="bg-amber-50 border border-amber-100 rounded-2xl p-7"><h2 class="text-xl font-bold text-gray-900 mb-3">Can improve after launch</h2><p class="text-sm text-gray-600 leading-relaxed">Additional content, advanced personalization, deep automation, experiments, and secondary integrations can follow when the core customer promise and operations are reliable.</p></div></section>

<section class="mt-16 max-w-3xl mx-auto"><h2 class="text-3xl font-extrabold text-gray-900 text-center mb-8">Shopify launch FAQs</h2><div class="space-y-4"><?php foreach($faqs as $faq): ?><details class="bg-white border border-gray-200 rounded-xl"><summary class="p-5 font-semibold cursor-pointer"><?= clean($faq['question']) ?></summary><p class="px-5 pb-5 text-gray-600 leading-relaxed"><?= clean($faq['answer']) ?></p></details><?php endforeach; ?></div></section>
</div></main>
<section class="bg-purple-800 py-14"><div class="max-w-3xl mx-auto px-4 text-center"><h2 class="text-3xl font-extrabold text-white">Want an expert launch partner?</h2><p class="text-purple-100 mt-3 mb-7">We design, build, test, and launch Shopify stores ready for growth.</p><a href="<?= url('services/shopify-growth') ?>" class="inline-flex px-7 py-3.5 bg-white text-purple-800 font-semibold rounded-xl">Explore Shopify growth</a></div></section>

<style>@media print{header,footer,nav,.filter-button,#print-checklist,#reset-checklist,.bg-purple-800{display:none!important}.checklist-group{break-inside:avoid;margin-bottom:16px}.sticky{position:static!important}body{background:white!important}}</style>
<script>
(function(){const boxes=[...document.querySelectorAll('.check-box')],key='akestech-shopify-launch-checklist-v1';let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch(e){}boxes.forEach(b=>{b.checked=!!saved[b.dataset.id];b.addEventListener('change',update)});
 function update(){const state={};boxes.forEach(b=>state[b.dataset.id]=b.checked);localStorage.setItem(key,JSON.stringify(state));const done=boxes.filter(b=>b.checked).length,pct=Math.round(done/boxes.length*100);document.getElementById('progress-label').textContent=done+' of '+boxes.length+' complete';document.getElementById('progress-percent').textContent=pct+'%';document.getElementById('progress-bar').style.width=pct+'%';document.querySelectorAll('.checklist-group').forEach(g=>{const all=[...g.querySelectorAll('.check-box')],d=all.filter(b=>b.checked).length;g.querySelector('.group-progress').textContent=d+'/'+all.length;all.forEach(b=>b.closest('label').querySelector('.item-text').classList.toggle('line-through',b.checked));all.forEach(b=>b.closest('label').querySelector('.item-text').classList.toggle('text-gray-400',b.checked))})}update();
 document.querySelectorAll('.filter-button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter-button').forEach(b=>{b.classList.remove('bg-purple-600','text-white');b.classList.add('bg-white','text-gray-700','border','border-gray-200')});btn.classList.add('bg-purple-600','text-white');btn.classList.remove('bg-white','text-gray-700','border','border-gray-200');document.querySelectorAll('.checklist-group').forEach(g=>g.classList.toggle('hidden',btn.dataset.filter!=='all'&&g.dataset.group!==btn.dataset.filter))}));
 document.getElementById('print-checklist').addEventListener('click',()=>window.print());document.getElementById('reset-checklist').addEventListener('click',()=>{if(confirm('Reset all checklist progress?')){boxes.forEach(b=>b.checked=false);update()}});
})();
</script>
<?php $pageContent=ob_get_clean(); SEO::renderSchemas($schemas); include __DIR__.'/../../includes/components/layout.php';
