<?php
SEO::set('meta_title', 'Free Shopify Speed Analyzer & Core Web Vitals Test | ' . SITE_NAME);
SEO::set('meta_description', 'Test your Shopify store speed on mobile or desktop. See performance score, Core Web Vitals, and prioritized recommendations powered by Google PageSpeed Insights.');
SEO::set('canonical_url', url('resources/shopify-speed-analyzer'));
SEO::set('og_title', 'Free Shopify Store Speed Analyzer');
SEO::set('og_description', 'Check performance, loading metrics, and the biggest opportunities slowing down your Shopify store.');
$faqs=[
 ['question'=>'What is a good Shopify speed score?','answer'=>'A Lighthouse performance score of 90 to 100 is considered good, 50 to 89 needs improvement, and below 50 is poor. Treat the score as a diagnostic indicator and prioritize real-user Core Web Vitals and conversion impact.'],
 ['question'=>'Why is my Shopify mobile score lower than desktop?','answer'=>'Mobile tests simulate a slower device and network, exposing heavy JavaScript, large images, app code, and rendering delays that powerful desktop devices can hide.'],
 ['question'=>'Do Shopify apps slow down a store?','answer'=>'Apps can add scripts, styles, tracking, and network requests. Some are essential and well optimized; others add meaningful delay or leave code behind after removal. Audit impact before removing revenue-critical functionality.'],
 ['question'=>'How can I improve Shopify speed?','answer'=>'Start with oversized images, video loading, unused app scripts, third-party tags, theme JavaScript, font loading, and layout shifts. Measure before and after each change on representative product and collection pages.'],
];
$schemas=[SEO::breadcrumbSchema([['name'=>'Home','url'=>url('/')],['name'=>'Resources','url'=>url('resources')],['name'=>'Shopify Speed Analyzer','url'=>url('resources/shopify-speed-analyzer')]]),SEO::faqSchema($faqs),json_encode(['@context'=>'https://schema.org','@type'=>'WebApplication','name'=>'Shopify Speed Analyzer','applicationCategory'=>'DeveloperApplication','operatingSystem'=>'Any','url'=>url('resources/shopify-speed-analyzer'),'offers'=>['@type'=>'Offer','price'=>'0','priceCurrency'=>'INR']],JSON_UNESCAPED_SLASHES)];
ob_start();
?>
<section class="bg-gradient-to-br from-cyan-950 via-slate-950 to-blue-950 py-16 lg:py-24"><div class="ak-container ak-pagehero__inner"><a href="<?= url('resources') ?>" class="text-sm text-cyan-300">&larr; Back to resources</a><p class="mt-6 text-xs font-bold uppercase tracking-[.2em] text-cyan-400">Free performance tool</p><h1 class="mt-3 text-4xl sm:text-5xl lg:text-6xl font-extrabold text-white">Shopify Speed Analyzer</h1><p class="mt-6 text-lg text-slate-300 max-w-3xl mx-auto">Test your store, review key loading metrics, and find the highest-impact speed improvements.</p>
<form id="speed-form" class="mt-9 max-w-3xl mx-auto bg-white rounded-2xl p-2 flex flex-col sm:flex-row gap-2 shadow-2xl"><label class="sr-only" for="store-url">Shopify store URL</label><input id="store-url" type="text" inputmode="url" placeholder="yourstore.com or product page URL" required class="flex-1 px-4 py-3 text-gray-900 outline-none rounded-xl"><select id="strategy" class="px-4 py-3 text-sm text-gray-700 bg-gray-50 rounded-xl outline-none" aria-label="Test device"><option value="mobile">Mobile</option><option value="desktop">Desktop</option></select><button id="analyze-button" type="submit" class="px-6 py-3 bg-cyan-600 hover:bg-cyan-700 text-white font-semibold rounded-xl">Analyze store</button></form><p class="mt-3 text-xs text-slate-400">Testing uses Google PageSpeed Insights. Results can vary between runs.</p></div></section>

<main class="ak-section"><div class="ak-container">
<div id="speed-placeholder" class="text-center py-12"><div class="w-16 h-16 mx-auto rounded-2xl bg-cyan-100 flex items-center justify-center text-3xl"><?= ak_icon('zap', 18) ?></div><h2 class="text-2xl font-bold text-gray-900 mt-5">Ready when your store is</h2><p class="text-gray-600 mt-2">Enter a public store or page URL above to start the test.</p></div>
<div id="speed-loading" class="hidden text-center py-16" role="status"><div class="w-12 h-12 mx-auto border-4 border-cyan-100 border-t-cyan-600 rounded-full animate-spin"></div><h2 class="text-xl font-bold text-gray-900 mt-5">Running a real performance test…</h2><p class="text-gray-500 mt-2">This often takes 20-60 seconds. Please keep this tab open.</p></div>
<div id="speed-error" class="hidden max-w-2xl mx-auto bg-red-50 border border-red-200 rounded-2xl p-6 text-center"><h2 class="text-xl font-bold text-red-900">We could not complete that test</h2><p id="speed-error-message" class="text-red-700 mt-2"></p><p class="text-sm text-red-600 mt-3">Check that the page is public, then retry. The testing service can also be temporarily rate-limited.</p></div>

<div id="speed-results" class="hidden">
    <div class="flex flex-col md:flex-row md:items-end md:justify-between gap-4 mb-7"><div><p class="text-xs font-bold uppercase tracking-wider text-cyan-600">Performance report</p><h2 id="tested-url" class="text-2xl font-bold text-gray-900 mt-1 break-all"></h2></div><p id="tested-at" class="text-sm text-gray-500"></p></div>
    <section class="grid lg:grid-cols-3 gap-6 mb-7"><div class="bg-white border border-gray-200 rounded-2xl p-7 flex flex-col items-center justify-center"><div id="score-ring" class="w-36 h-36 rounded-full flex items-center justify-center" style="background:conic-gradient(#06b6d4 0%,#e5e7eb 0)"><div class="w-28 h-28 rounded-full bg-white flex flex-col items-center justify-center"><strong id="speed-score" class="text-4xl font-extrabold">0</strong><span class="text-xs text-gray-500">Performance</span></div></div><p id="score-label" class="mt-4 font-semibold"></p></div>
    <div class="lg:col-span-2 grid sm:grid-cols-2 gap-4" id="metric-grid"></div></section>
    <section class="bg-white border border-gray-200 rounded-2xl overflow-hidden"><div class="p-6 border-b border-gray-100"><h2 class="text-2xl font-bold text-gray-900">Prioritized opportunities</h2><p class="text-sm text-gray-500 mt-1">Start at the top, but test business impact before removing store features.</p></div><div id="opportunities" class="divide-y divide-gray-100"></div></section>
</div>

<section class="mt-16 grid lg:grid-cols-3 gap-6"><div class="lg:col-span-2 bg-white border border-gray-200 rounded-2xl p-7"><h2 class="text-2xl font-bold text-gray-900 mb-5">What slows Shopify stores down?</h2><div class="grid sm:grid-cols-2 gap-5"><?php foreach([['App and tag JavaScript','Review scripts from apps, analytics, chat, reviews, and marketing tags.'],['Unoptimized media','Resize images to rendered dimensions and avoid autoplaying heavy video above the fold.'],['Theme code','Remove unused sections and libraries; defer work that is not needed for the first screen.'],['Layout shifts','Reserve image, banner, and app-widget space so content does not jump while loading.']] as $item): ?><div><h3 class="font-semibold text-gray-900"><?= $item[0] ?></h3><p class="text-sm text-gray-600 mt-1 leading-relaxed"><?= $item[1] ?></p></div><?php endforeach; ?></div></div><div class="bg-cyan-50 border border-cyan-100 rounded-2xl p-7"><h2 class="ak-h3">Test the right pages</h2><p class="text-sm text-gray-600 leading-relaxed">Your homepage is not the whole store. Test your highest-traffic product, collection, campaign landing, cart, and a content-heavy page on mobile.</p></div></section>

<section class="ak-container ak-narrow"><h2 class="ak-h3 ak-center">Shopify speed FAQs</h2><div class="space-y-4"><?php foreach($faqs as $faq): ?><details class="ak-details"><summary class="ak-details__q"><?= clean($faq['question']) ?></summary><p class="ak-details__a"><?= clean($faq['answer']) ?></p></details><?php endforeach; ?></div></section>
</div></main>
<section class="bg-cyan-800 py-14"><div class="ak-container ak-narrow"><h2 class="ak-h2 ak-onDark">Need expert Shopify optimization?</h2><p class="text-cyan-100 mt-3 mb-7">We improve speed without blindly removing the apps and features that drive revenue.</p><a href="<?= url('services/technology') ?>" class="inline-flex px-7 py-3.5 bg-white text-cyan-800 font-semibold rounded-xl">Explore technology services</a></div></section>

<script>
(function(){
 const form=document.getElementById('speed-form'),placeholder=document.getElementById('speed-placeholder'),loading=document.getElementById('speed-loading'),errorBox=document.getElementById('speed-error'),results=document.getElementById('speed-results'),button=document.getElementById('analyze-button');
 const metricIds=[['largest-contentful-paint','Largest Contentful Paint'],['cumulative-layout-shift','Cumulative Layout Shift'],['interaction-to-next-paint','Interaction to Next Paint'],['total-blocking-time','Total Blocking Time'],['first-contentful-paint','First Contentful Paint'],['speed-index','Speed Index']];
 const show=name=>{[placeholder,loading,errorBox,results].forEach(el=>el.classList.add('hidden'));name.classList.remove('hidden')};
 const color=score=>score>=.9?'#16a34a':score>=.5?'#f59e0b':'#dc2626';
 form.addEventListener('submit',async e=>{e.preventDefault();let url=document.getElementById('store-url').value.trim();if(!/^https?:\/\//i.test(url))url='https://'+url;try{new URL(url)}catch(_){document.getElementById('speed-error-message').textContent='Please enter a valid store URL.';show(errorBox);return}
  show(loading);button.disabled=true;const strategy=document.getElementById('strategy').value;
  try{const endpoint='https://www.googleapis.com/pagespeedonline/v5/runPagespeed?category=performance&strategy='+strategy+'&url='+encodeURIComponent(url);const response=await fetch(endpoint);const data=await response.json();if(!response.ok||!data.lighthouseResult)throw new Error(data.error?.message||'The performance service did not return a report.');render(data,url)}catch(err){document.getElementById('speed-error-message').textContent=err.message;show(errorBox)}finally{button.disabled=false}
 });
 function render(data,url){const lh=data.lighthouseResult,audits=lh.audits,score=Math.round((lh.categories.performance.score||0)*100);document.getElementById('tested-url').textContent=url;document.getElementById('tested-at').textContent='Tested '+new Date().toLocaleString();document.getElementById('speed-score').textContent=score;document.getElementById('score-label').textContent=score>=90?'Good':score>=50?'Needs improvement':'Poor';document.getElementById('score-label').style.color=color(score/100);document.getElementById('score-ring').style.background='conic-gradient('+color(score/100)+' '+score+'%,#e5e7eb '+score+'%)';
  const grid=document.getElementById('metric-grid');grid.innerHTML='';metricIds.forEach(([id,label])=>{const a=audits[id];if(!a)return;const card=document.createElement('div');card.className='bg-white border border-gray-200 rounded-2xl p-5';card.innerHTML='<div class="flex items-center justify-between gap-3"><p class="text-sm text-gray-500">'+label+'</p><span class="w-2.5 h-2.5 rounded-full" style="background:'+color(a.score===null?0:a.score)+'"></span></div><p class="text-2xl font-extrabold text-gray-900 mt-2">'+(a.displayValue||'—')+'</p>';grid.appendChild(card)});
  let ops=Object.values(audits).filter(a=>a.details&&a.details.type==='opportunity'&&a.score!==null&&a.score<.9).sort((a,b)=>(b.details.overallSavingsMs||0)-(a.details.overallSavingsMs||0)).slice(0,8);const box=document.getElementById('opportunities');box.innerHTML='';if(!ops.length)box.innerHTML='<p class="p-6 text-gray-600">No major loading opportunities were reported. Review diagnostics and real-user data before concluding the page is fully optimized.</p>';ops.forEach((a,i)=>{const row=document.createElement('div');row.className='p-6 flex gap-4';row.innerHTML='<span class="w-8 h-8 shrink-0 rounded-full bg-cyan-50 text-cyan-700 font-bold flex items-center justify-center">'+(i+1)+'</span><div><h3 class="font-semibold text-gray-900">'+a.title+'</h3><p class="text-sm text-gray-600 mt-1 leading-relaxed">'+(a.description||'Review this opportunity in the full performance audit.').replace(/\[([^\]]+)\]\([^\)]+\)/g,'$1')+'</p><p class="text-xs font-semibold text-cyan-700 mt-2">'+(a.displayValue||'')+'</p></div>';box.appendChild(row)});show(results);results.scrollIntoView({behavior:'smooth',block:'start'})}
})();
</script>
<?php $pageContent=ob_get_clean(); SEO::renderSchemas($schemas); include __DIR__.'/../../includes/components/layout.php';
